### PR TITLE
Dialogue box

### PR DESCRIPTION
**Pull request by stormon-force**
Updated dialogue box, dialogue now appears and is relatively consistent.

initiate with left click.

 --- Current issues ---
No current way to despawn dialogue box from room after dialogue box 
Josh

### CODE REVIEW

**Comment by SeanMachen845** [comment]
@stormon-force rad, I'll take a look later tonight when I get back home

**Comment by SeanMachen845** [comment]
@stormon-force Did you put another project inside this project when you pushed up your branch? 10,000+ lines and 180 files changed seems super hefty. Also I am seeing a lot of css and javascript that should not be related to this project.

**Comment by SeanMachen845** [comment]
@stormon-force I made a few changes to your branch mind taking a look at the new changes. I cleaned up the code a bit, refactored naming for Objects and Sprites, and added the ability to close text boxes.

**Review by SeanMachen845 — APPROVED** [review]
🐑 :shipit:

**Comment by stormon-force** [comment]
thanks dad

**Pull request merged**
