### PR TITLE
Added Stamina and Sprinting

### PR DESCRIPTION
**Pull request by SeanMachen845**
- Added the ability to sprint by holding shift 
 - Added a stamina system which makes decreases in value the less stamina you have (e.g. less stamina slower sprint)
 - Added a placeholder stamina bar which disappears when stamina is full

### CODE REVIEW

**Comment by jessebodin** [comment]
Looks good. Stamina still drains if you push into a wall while sprinting.

**Review by jessebodin — CHANGES_REQUESTED** [review]
Stamina still drains if you're pressed into a wall while sprinting.

**Comment by SeanMachen845** [comment]
@jessebodin Good find, I'll fix this guy up when I get back home tonight

**Review by jessebodin — APPROVED** [review]

**Comment by jessebodin** [comment]
Nicely done. Everything looks good.

**Pull request merged**
